### ISSUE TITLE
SymLog Scale does not correspond the range and the domain values when scaling and inverting.

### ISSUE THREAD

**Issue by jordanmontt** [ObjectProfile/Roassal3#531]
The NSSymLogScale is not corresponding the range and the domain values when scaling and inverting.

To reproduce, create a test and run the following code:

```st
scale := NSSymLogScale  new
    domain: { 1. 70000 };
    range: { 1. 2 }.
self assert: scale domain first closeTo: (scale invert: scale range first).
self assert: scale domain second closeTo: (scale invert: scale range second)
```

You will see a failure when the two assertions should give true.

**Comment by akevalion** [comment]
fixed with this pr
https://github.com/ObjectProfile/NumericScales/pull/7

**Comment by PalumboN** [comment]
But the PR https://github.com/ObjectProfile/NumericScales/pull/7 just added a test, right? The problem is not fixed 😞

**Comment by jordanmontt** [comment]
But the changes are not integrated neither in Rossal nor Pharo

**Comment by PalumboN** [comment]
It will! 🤖 

Why NumericScales is in another repo? There are others projects that use it?

**Comment by jordanmontt** [comment]
The random numbers generator uses the linear scale if I recall correctly. So all the dependencies to random numbers depend also on numeric scales.

**Comment by PalumboN** [comment]
But Pharo also depends on Roassal too :P

**Comment by akevalion** [comment]
Hi, I will prepare a new release at the end of this week.
By now only roassal depends on NumericScales.
Numeric scales its a separated project because it is only for number scaling, not visualization, but yes it is used by roassal2 and roassal3. As far as I know no other project uses NSScale

**Comment by akevalion** [comment]
I can not find dependency of Random-Core to NumericScales
<img width="454" alt="image" src="https://user-images.githubusercontent.com/10532890/234339825-15c7867d-c881-4d7b-b7ed-fa218bd28196.png">

Actually NumericScales has the dependency to Random-Core 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/10532890/234340724-4717f517-e312-4b94-8223-be3e4d68ef7c.png">
